### PR TITLE
Updated to support parallel indexing.

### PR DESCRIPTION
**Pull request by acalhounRH**
Added support for to handle larger loads with the use of parallel indexing.

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Consider something like https://github.com/acalhounRH/py-es-bulk/pull/1.

**Comment by acalhounRH** [comment]
Accepted/Merged PR, ready for review/merge

**Review by dbutenhof — COMMENTED** [review]
Ideally there should be (at least one) new unit test for the change that fails without it; probably a clone of `streaming_bulk_test.py`

**Comment by portante** [comment]
Actually, one more, we need a unit test: https://github.com/acalhounRH/py-es-bulk/pull/2.

**Review by portante — APPROVED** [review]
Ship it!

**Review by dbutenhof — APPROVED** [review]
Darn; I guess this means I'm going to have to do the merge. ;-)

**Pull request merged**
